### ISSUE TITLE
I found a bug while running the process.

### ISSUE THREAD

**Issue by rayhhhhh** [Jaroan/Fair-MARL#1]
File "\Fair-MARL-main\marl_fair_assign.py", line 38, in solve_fair_assignment
    x = np.array(pe.value(m.x[:,:])).reshape((n,nj)).astype(int)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Jaroan** [comment]
Thanks for catching it! Could you make a pull request regarding this change?

**Comment by hsvgbkhgbv** [comment]
I also meet this bug. I suppose that it is led by the bugs from Gorubi solver.

**Comment by hsvgbkhgbv** [comment]
This bug is due to setting num_agents < num_landmarks

**Comment by Jaroan** [comment]
Thanks, @hsvgbkhgbv; I've fixed this in the latest update!
